import type { CueConfig,CueKind } from '../shared/types';
export type ParticleEvent={radius:number;spread:number;brightness:number;opacity:number;visibility:number;radialForce:number;swirl:number;centerHole:number;randomForce:number;verticalFall:number;glow:number;flicker:number;originReturn:number;ambientInfluence:number};
export const neutralEvent=():ParticleEvent=>({radius:1,spread:0,brightness:1,opacity:1,visibility:1,radialForce:0,swirl:0,centerHole:0,randomForce:0,verticalFall:0,glow:0,flicker:0,originReturn:0,ambientInfluence:1});
const clamp=(x:number)=>Math.max(0,Math.min(1,x));
const smooth=(x:number)=>{x=clamp(x);return x*x*(3-2*x);};
const mix=(a:ParticleEvent,b:ParticleEvent,t:number)=>Object.fromEntries(Object.keys(a).map(key=>{const k=key as keyof ParticleEvent;return[k,a[k]+(b[k]-a[k])*t];})) as ParticleEvent;
export function emotionTarget(kind:CueKind):ParticleEvent{const e=neutralEvent();switch(kind){case'doubt':e.spread=.035;e.brightness=1.22;e.glow=.7;e.flicker=.16;e.randomForce=.12;break;case'explore':e.radialForce=.56;e.radius=1.18;e.centerHole=.32;e.spread=.018;break;case'desire':e.radialForce=-.48;e.radius=.68;e.swirl=1.1;e.glow=.2;break;case'confidence':e.randomForce=-.72;e.ambientInfluence=.12;e.originReturn=.7;e.glow=.52;e.brightness=1.12;break;case'conflict':e.randomForce=1.25;e.spread=.11;e.flicker=.42;e.glow=.25;break;case'void':e.verticalFall=.78;e.radius=1.08;e.brightness=.08;e.opacity=.12;e.visibility=.18;e.glow=.06;e.ambientInfluence=.08;break;case'acceptance':e.originReturn=1;e.ambientInfluence=1;e.brightness=1.12;e.glow=.25;break;case'finalDissolve':e.radius=1.45;e.spread=.14;e.brightness=0;e.opacity=0;e.visibility=0;e.ambientInfluence=0;break;}return e;}
function entering(kind:CueKind,t:number,target:ParticleEvent){const e=mix(neutralEvent(),target,smooth(t));if(kind==='doubt'){const flash=Math.sin(Math.PI*clamp(t/.45))**2;e.brightness+=.65*flash;e.glow+=.35*flash;}if(kind==='confidence')e.glow+=.55*Math.sin(Math.PI*clamp(t));if(kind==='conflict')e.randomForce*=.55+.45*Math.sin(Math.PI*clamp(t/.25))**2;if(kind==='void'){const bloom=Math.sin(Math.PI*clamp(t/.32))**2;e.brightness+=1.5*bloom;e.glow+=1.35*bloom;}if(kind==='acceptance'){e.brightness=.12+.88*smooth(t);e.opacity=.15+.85*smooth(t);e.visibility=.2+.8*smooth(t);}return e;}
export class CueRuntime{private active?:{index:number;start:number;from:ParticleEvent;config:CueConfig};private last=neutralEvent();private final?:{start:number;from:ParticleEvent;duration:number};get isEnding(){return Boolean(this.final);}get activeIndex(){return this.active?.index;}
  trigger(index:number,now=performance.now(),config?:CueConfig){if(this.final)return;if(index===7){this.final={start:now,from:{...this.last},duration:config?.durationMs??5000};this.active=undefined;return;}if(index<0||index>6||!config)return;this.active={index,start:now,from:{...this.last},config:{...config}};}
  deactivate(now=performance.now(),duration=1800){this.active={index:-1,start:now,from:{...this.last},config:{kind:'acceptance',label:'Ambient',durationMs:duration,intensity:1}};}
  reset(){this.active=undefined;this.final=undefined;this.last=neutralEvent();}
  resolve(_cues:CueConfig[],now=performance.now()):ParticleEvent{if(this.final){const t=smooth((now-this.final.start)/Math.max(300,this.final.duration));return this.last=mix(this.final.from,emotionTarget('finalDissolve'),t);}if(!this.active)return this.last=neutralEvent();const{index,start,from,config}=this.active,t=clamp((now-start)/Math.max(300,config.durationMs));if(index<0){if(t>=1){this.active=undefined;return this.last=neutralEvent();}return this.last=mix(from,neutralEvent(),smooth(t));}const target=mix(neutralEvent(),emotionTarget(config.kind),clamp(config.intensity));return this.last=mix(from,entering(config.kind,t,target),smooth(t/.18));}}
export const cueKinds:{value:CueKind;label:string}[]=[{value:'doubt',label:'怀疑'},{value:'explore',label:'探索'},{value:'desire',label:'欲望'},{value:'confidence',label:'自信'},{value:'conflict',label:'冲突'},{value:'void',label:'虚无'},{value:'acceptance',label:'接纳'},{value:'finalDissolve',label:'结束 · 光芒消散'}];
