import type { ArduinoConfig } from './arduino';
export type ChannelTuple = [number, number, number, number, number, number, number, number];
export type SensorFrame = { version: 1; seq: number; channels: ChannelTuple; final: 0 | 1; touch?: import('./touch').TouchTelemetry };
export type InputEnvelope = { threshold: number; hysteresis: number; smoothingMs: number; attackMs: number; releaseMs: number; invert: boolean; calibrationMin: number; calibrationMax: number };
export type EffectValue = { raw: number; normalized: number; triggered: boolean; envelope: number };
export type GlobalState = 'running' | 'final-releasing' | 'standby';
export type MappingQuad = { topLeft: [number, number]; topRight: [number, number]; bottomRight: [number, number]; bottomLeft: [number, number] };
export type MappingGrid = { columns: 3 | 5; rows: 3 | 5; points: [number, number][] };
export type EffectId = 'disperse' | 'blocks' | 'warp' | 'vortex' | 'lightPath' | 'tide';
export type CueKind = 'doubt' | 'explore' | 'desire' | 'confidence' | 'conflict' | 'void' | 'acceptance' | 'finalDissolve';
export type CueConfig = { kind: CueKind; label: string; durationMs: number; transitionMs: number; intensity: number };
export type EmotionSequenceConfig={autoPlay:boolean;globalDelayMs:number;steps:{useGlobal:boolean;delayMs:number;next:number}[]};
export type AmbientConfig = { enabled: boolean; amplitude: number; speed: number; randomness: number; force: number; direction: number; movementRange: number; trail: number };
export type QuantumConfig = { pointSize: number; brightness: number; edgeFeather: number };
export type PlaylistItem = { id: string; assetId: string; durationMs: number };
export type BlendMode = 'normal' | 'add' | 'screen';
export type NodeKind = 'sensor' | 'constant' | 'time' | 'mapping' | 'media' | 'effect' | 'uv' | 'output' | 'final';
export type StudioNode = { id: string; kind: NodeKind; label: string; position: { x: number; y: number }; channel?: number | 'final'; effectId?: EffectId; envelope?: InputEnvelope; value?: number };
export type StudioEdge = { id: string; source: string; target: string; targetParam?: 'intensity' | 'trigger'; combine?: 'max' | 'sum'; enabled?: boolean };
export type MediaAsset = { id: string; name: string; path: string; type: 'image' | 'video'; missing?: boolean };
export type EffectConfig = { enabled: boolean; intensity: number; attackMs: number; releaseMs: number; blendMode: BlendMode; referenceMediaId?: string };
export type StudioProject = {
  formatVersion: 1; name: string; nodes: StudioNode[]; edges: StudioEdge[]; assets: MediaAsset[];
  activeMediaId?: string; standbyMediaId?: string; effects: Record<EffectId, EffectConfig>;
  cues: CueConfig[];
  ambient: AmbientConfig;
  quantum: QuantumConfig;
  arduino: ArduinoConfig;
  ui: { language: 'zh' | 'en'; layout:{leftWidth:number;rightWidth:number;previewHeight:number} };
  emotionSequence:EmotionSequenceConfig;
  routing: { enabled: boolean };
  playlist: { enabled: boolean; loop: boolean; mode: 'timed' | 'triggered'; advanceChannel: number | 'manual'; items: PlaylistItem[] };
  mapping: { quad: MappingQuad; controlMode: 'basic' | 'grid'; editorLayer:'uv'|'source';grid: MappingGrid;sourceFrame:{x:number;y:number;width:number;height:number};previewMode:'eco'|'standard'|'high'|'1080p'|'auto';previewScale: .25 | .5 | .75; fit: 'fill' | 'fit' | 'stretch'; rotation: 0 | 90 | 180 | 270; mirrorX: boolean; mirrorY: boolean; brightness: number; blackout: boolean; locked: boolean; displayId?: number };
  serial: { path?: string; baudRate: 115200; channels: InputEnvelope[]; finalSource: number | 'final'; finalReleaseMs: number };
};
export type DisplayInfo = { id: number; label: string; bounds: { x: number; y: number; width: number; height: number }; primary: boolean };
export type SerialPortInfo = { path: string; manufacturer?: string; serialNumber?: string };
export type PerformanceInfo = { fps: number; frameMs: number; quality: 'high' | 'medium' | 'low'; serialConnected: boolean; globalState: GlobalState };
export type OutputSnapshot = { particleEvent?: import('../runtime/particle-events').ParticleEvent; project: StudioProject; effectValues: Record<EffectId, number>; transition: { nextMediaId?: string; progress: number } };
