import type { CueConfig, DisplayInfo, MediaAsset, SerialPortInfo, StudioNode, StudioProject } from '../shared/types';
import { cueKinds } from '../runtime/cues';
import { cueLabel, text, type Language } from '../i18n';

export function MediaPanel({language,assets,active,onImport,onSelect,onLocate,onDelete}:{language:Language;assets:MediaAsset[];active?:string;onImport:()=>void;onSelect:(id:string)=>void;onLocate:(asset:MediaAsset)=>void;onDelete:(id:string)=>void}){
  return <section className="side-section media-section"><header><span>01</span><b>{text(language,'素材库','MEDIA LIBRARY')}</b><button onClick={onImport}>＋ {text(language,'导入','IMPORT')}</button></header><div className="media-list">{assets.length===0?<div className="empty-small">JPG · PNG · WEBP<br/>MP4 · WEBM</div>:assets.map(asset=><div key={asset.id} style={{display:'grid',gridTemplateColumns:'1fr 28px',gap:4}}><button className={`${active===asset.id?'active':''} ${asset.missing?'missing':''}`} onClick={()=>asset.missing?onLocate(asset):onSelect(asset.id)}><i>{asset.missing?'!':asset.type==='video'?'▶':'▧'}</i><span>{asset.name}</span></button><button title={text(language,'从素材库删除','Remove from library')} aria-label={`${text(language,'删除','Remove')} ${asset.name}`} onClick={()=>onDelete(asset.id)} style={{color:'#ff7659',padding:0}}>×</button></div>)}</div></section>;
}

export function SensorPanel({language,values,cues,connected,ports,onConnect,onVirtual,onTrigger}:{language:Language;values:number[];cues:CueConfig[];connected:boolean;ports:SerialPortInfo[];onConnect:(path?:string)=>void;onVirtual:(index:number,value:number)=>void;onTrigger:(index:number)=>void}){
  return <section className="side-section sensor-section"><header><span>02</span><b>{text(language,'7 个 EVENT + CH8 结束','7 EVENTS + CH8 END')}</b><em className={connected?'online':''}>{connected?'ONLINE':'VIRTUAL'}</em></header><div style={{display:'grid',gap:7}}>{values.map((value,index)=><div key={index} style={{padding:'7px',border:'1px solid #272b28',background:'#111411'}}><div style={{display:'flex',alignItems:'center',gap:6,marginBottom:5}}><b style={{fontSize:9,color:'#b7e774'}}>CH {index+1}</b><span style={{fontSize:10,flex:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{cues[index]&&cueLabel(cues[index].kind,language)}</span><output style={{fontSize:9,color:'#858b85'}}>{value.toFixed(2)}</output></div><div style={{display:'grid',gridTemplateColumns:'1fr 58px',gap:5}}><input type="range" min="0" max="1" step=".01" value={value} onChange={e=>onVirtual(index,+e.target.value)}/><button onClick={()=>onTrigger(index)} style={{fontSize:8,color:'#ff9b82'}}>TRIGGER</button></div></div>)}</div><div className="connect-row"><select id="serial-port"><option value="">{text(language,'选择 USB 串口','SELECT USB PORT')}</option>{ports.map(port=><option key={port.path} value={port.path}>{port.path} {port.manufacturer}</option>)}</select><button onClick={()=>onConnect((document.querySelector('#serial-port') as HTMLSelectElement).value||undefined)}>{connected?text(language,'断开','DISCONNECT'):text(language,'连接','CONNECT')}</button></div></section>;
}

export function Inspector({language,project,selected,onProject}:{language:Language;project:StudioProject;selected?:StudioNode;onProject:(project:StudioProject)=>void}){
  if(!selected)return <aside className="inspector"><div className="inspector-empty">{text(language,'选择一个节点','SELECT A NODE')}<br/><small>{text(language,'配置输入、效果或输出','Configure input, effect or output')}</small></div></aside>;
  const effect=selected.effectId?project.effects[selected.effectId]:undefined;
  const cue=typeof selected.channel==='number'?project.cues[selected.channel]:undefined;
  const updateEffect=(key:string,value:unknown)=>onProject({...project,effects:{...project.effects,[selected.effectId!]:{...effect,[key]:value}}});
  const updateEnvelope=(key:string,value:number|boolean)=>onProject({...project,nodes:project.nodes.map(n=>n.id===selected.id?{...n,envelope:{...n.envelope!,[key]:value}}:n)});
  const updateCue=(value:Partial<CueConfig>)=>{const channel=selected.channel as number;const cues=project.cues.map((item,index)=>index===channel?{...item,...value}:item);const cue=cues[channel];const nodes=project.nodes.map(node=>node.channel===channel?{...node,label:`CH ${channel+1} · ${cue.label}`}:node);onProject({...project,cues,nodes});};
  const title=cue&&typeof selected.channel==='number'?`CH ${selected.channel+1} · ${cueLabel(cue.kind,language)}`:selected.label;
  return <aside className="inspector"><header><small>{selected.kind}</small><h2>{title}</h2></header>{cue&&<div className="form-stack"><label className="field"><span>{text(language,'情绪视觉状态','EMOTION VISUAL STATE')}</span><select disabled value={cue.kind} onChange={e=>{const option=cueKinds.find(item=>item.value===e.target.value)!;updateCue({kind:option.value,label:option.label});}}>{cueKinds.map(item=><option key={item.value} value={item.value}>{cueLabel(item.value,language)}</option>)}</select></label><Range label={text(language,'Cue 强度','Cue Intensity')} value={cue.intensity} min={0} max={1.5} step={.05} onChange={v=>updateCue({intensity:v})}/><Range label={text(language,'缓进缓出 ms','Crossfade ms')} value={cue.transitionMs} min={250} max={6000} step={100} onChange={v=>updateCue({transitionMs:v})}/></div>}{effect&&<div className="form-stack"><Toggle label={text(language,'启用效果','Enable Effect')} value={effect.enabled} onChange={v=>updateEffect('enabled',v)}/><Range label={text(language,'基础强度','Base Intensity')} value={effect.intensity} min={0} max={1} step={.01} onChange={v=>updateEffect('intensity',v)}/></div>}{selected.envelope&&<div className="form-stack"><Range label={text(language,'触发阈值','Trigger Threshold')} value={selected.envelope.threshold} min={0} max={1} step={.01} onChange={v=>updateEnvelope('threshold',v)}/><Range label={text(language,'迟滞','Hysteresis')} value={selected.envelope.hysteresis} min={0} max={.4} step={.01} onChange={v=>updateEnvelope('hysteresis',v)}/><Range label={text(language,'平滑 ms','Smoothing ms')} value={selected.envelope.smoothingMs} min={0} max={2000} step={10} onChange={v=>updateEnvelope('smoothingMs',v)}/></div>}</aside>;
}
const Range=({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(v:number)=>void})=><label className="field"><span>{label}<output>{value}</output></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(+e.target.value)}/></label>;
const Toggle=({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void})=><label className="toggle"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>;

export function OutputControls({language,project,displays,outputOpen,onProject,onOpen,onClose,onRefresh}:{language:Language;project:StudioProject;displays:DisplayInfo[];outputOpen:boolean;onProject:(project:StudioProject)=>void;onOpen:()=>void;onClose:()=>void;onRefresh:()=>void}){
  const mapping=project.mapping;const set=(value:Partial<typeof mapping>)=>onProject({...project,mapping:{...mapping,...value}});
  return <div className="output-controls"><select value={mapping.displayId??''} onChange={e=>set({displayId:+e.target.value})}><option value="">{text(language,'选择投影显示器','SELECT PROJECTOR DISPLAY')}</option>{displays.map(d=><option key={d.id} value={d.id}>{d.label}{d.primary?text(language,' · 主屏',' · PRIMARY'):''}</option>)}</select><button className={outputOpen?'active':''} onClick={onOpen}>{outputOpen?text(language,'重新开启投影','REOPEN OUTPUT'):text(language,'开启投影','OPEN OUTPUT')}</button>{outputOpen&&<button onClick={onClose}>{text(language,'关闭投影','CLOSE OUTPUT')}</button>}<button onClick={onRefresh}>{text(language,'刷新显示','REFRESH DISPLAY')}</button><button className={mapping.blackout?'danger active':''} onClick={()=>set({blackout:!mapping.blackout})}>BLACKOUT</button><label>{text(language,'亮度','BRIGHTNESS')} <input type="range" min="0" max="1" step=".01" value={mapping.brightness} onChange={e=>set({brightness:+e.target.value})}/></label><button onClick={()=>set({locked:!mapping.locked})}>{mapping.locked?text(language,'解锁 UV','UNLOCK UV'):text(language,'锁定 UV','LOCK UV')}</button></div>;
}

export function AmbientPanel({language,project,onProject}:{language:Language;project:StudioProject;onProject:(project:StudioProject)=>void}){const ambient=project.ambient,quantum=project.quantum;const set=(value:Partial<typeof ambient>)=>onProject({...project,ambient:{...ambient,...value}});const setQuantum=(value:Partial<typeof quantum>)=>onProject({...project,quantum:{...quantum,...value}});return <div className="mapping-tools"><h2>{text(language,'常态量子点力场','AMBIENT QUANTUM FIELD')}</h2><p>{text(language,'导入素材后，图片或视频会持续映射到填满画面的量子点，并始终受统一引力场影响。特效运动在边缘逐渐衰减，画面最外沿保持原位；特效亮度在基础粒子亮度上叠加。','Media continuously maps to the full quantum-dot field. Event motion fades toward the edge so the outermost particles stay anchored; event brightness is added on top of the base particle brightness.')}</p><div className="form-stack" style={{maxWidth:620}}><Toggle label={text(language,'启用常态力场','Enable Ambient Field')} value={ambient.enabled} onChange={v=>set({enabled:v})}/><Range label={text(language,'基础粒子亮度','Base Particle Brightness')} value={quantum.brightness} min={0} max={2} step={.01} onChange={v=>setQuantum({brightness:v})}/><Range label={text(language,'特效边缘保护范围','Event Edge Protection')} value={quantum.edgeFeather} min={.02} max={.5} step={.01} onChange={v=>setQuantum({edgeFeather:v})}/><Range label={text(language,'潮汐幅度','Tidal Amplitude')} value={ambient.amplitude} min={0} max={1.5} step={.01} onChange={v=>set({amplitude:v})}/><Range label={text(language,'流动速率','Flow Speed')} value={ambient.speed} min={0} max={2} step={.01} onChange={v=>set({speed:v})}/><Range label={text(language,'全局力随机性','Global Force Randomness')} value={ambient.randomness} min={0} max={1} step={.01} onChange={v=>set({randomness:v})}/><Range label={text(language,'统一引力大小','Gravity Strength')} value={ambient.force} min={0} max={1.5} step={.01} onChange={v=>set({force:v})}/><Range label={text(language,'引力方向 °','Gravity Direction °')} value={ambient.direction} min={-180} max={180} step={1} onChange={v=>set({direction:v})}/><Range label={text(language,'移动范围','Movement Range')} value={ambient.movementRange} min={0} max={2} step={.01} onChange={v=>set({movementRange:v})}/><Range label={text(language,'轨迹保留','Trail Persistence')} value={ambient.trail} min={0} max={.97} step={.01} onChange={v=>set({trail:v})}/><Range label={text(language,'量子点尺寸','Quantum Dot Size')} value={quantum.pointSize} min={.4} max={3} step={.05} onChange={v=>setQuantum({pointSize:v})}/></div></div>;}

export function TimelinePanel({language,project,playing,onProject,onPlay,onSelect,onNext}:{language:Language;project:StudioProject;playing:boolean;onProject:(project:StudioProject)=>void;onPlay:(value:boolean)=>void;onSelect:(assetId:string)=>void;onNext:()=>void}){
  const list=project.playlist;const setList=(value:Partial<typeof list>)=>onProject({...project,playlist:{...list,...value}});const setItems=(items:typeof list.items)=>setList({items});
  const move=(index:number,delta:number)=>{const items=[...list.items],target=index+delta;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];setItems(items);};
  return <div className="mapping-tools"><h2>{text(language,'素材时间线','MEDIA TIMELINE')}</h2><p>{text(language,'计时模式自动前进；条件模式只有点击 NEXT 或指定 CH 产生一次新触发时才切换轨道。','Timed mode advances automatically. Triggered mode changes tracks only when NEXT is pressed or the selected CH produces a new trigger.')}</p><div className="output-controls"><button className={playing?'active':''} onClick={()=>onPlay(!playing)}>{playing?text(language,'停止','STOP'):text(language,'▶ 启用时间线','▶ ENABLE TIMELINE')}</button><label>{text(language,'推进方式','ADVANCE MODE')} <select value={list.mode} onChange={e=>setList({mode:e.target.value as 'timed'|'triggered'})}><option value="timed">{text(language,'按时间自动','TIMED AUTO')}</option><option value="triggered">{text(language,'仅按键 / 条件','BUTTON / CONDITION')}</option></select></label>{list.mode==='triggered'&&<><label>{text(language,'触发条件','TRIGGER SOURCE')} <select value={list.advanceChannel} onChange={e=>setList({advanceChannel:e.target.value==='manual'?'manual':+e.target.value})}><option value="manual">{text(language,'仅 NEXT 按钮','NEXT BUTTON ONLY')}</option>{Array.from({length:8},(_,index)=><option key={index} value={index}>CH {index+1}</option>)}</select></label><button onClick={onNext}>NEXT →</button></>}<label><input type="checkbox" checked={list.loop} onChange={e=>setList({loop:e.target.checked})}/> {text(language,'循环','LOOP')}</label></div><div style={{display:'grid',gap:6,marginTop:14}}>{list.items.map((item,index)=>{const asset=project.assets.find(a=>a.id===item.assetId);return <div key={item.id} style={{display:'grid',gridTemplateColumns:'34px 1fr 100px 30px 30px 30px',gap:5,alignItems:'center',padding:8,border:'1px solid #272b28'}}><b>{String(index+1).padStart(2,'0')}</b><button onClick={()=>onSelect(item.assetId)} style={{textAlign:'left',overflow:'hidden',textOverflow:'ellipsis'}}>{asset?.name??text(language,'缺失素材','MISSING MEDIA')}</button><label style={{fontSize:10,opacity:list.mode==='timed'?1:.45}}><input type="number" disabled={list.mode!=='timed'} min={.2} max={120} step={.1} value={item.durationMs/1000} onChange={e=>setItems(list.items.map(row=>row.id===item.id?{...row,durationMs:+e.target.value*1000}:row))} style={{width:55}}/> {text(language,'秒','SEC')}</label><button onClick={()=>move(index,-1)}>↑</button><button onClick={()=>move(index,1)}>↓</button><button onClick={()=>setItems(list.items.filter(row=>row.id!==item.id))}>×</button></div>})}</div><div style={{marginTop:14,display:'flex',flexWrap:'wrap',gap:5}}>{project.assets.filter(asset=>!list.items.some(item=>item.assetId===asset.id)).map(asset=><button key={asset.id} onClick={()=>setItems([...list.items,{id:`playlist-${crypto.randomUUID()}`,assetId:asset.id,durationMs:5000}])}>＋ {asset.name}</button>)}</div></div>;
}
