import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createDefaultProject, defaultGrid } from './shared/defaults';
import type { DisplayInfo, EffectId, PerformanceInfo, SensorFrame, SerialPortInfo, StudioProject } from './shared/types';
import { EnvelopeProcessor } from './runtime/envelope';
import { GlobalStateMachine } from './runtime/global-state';
import { CueRuntime } from './runtime/cues';
import { EmotionSequence } from './runtime/emotion-sequence';
import { resolveEffectValues } from './runtime/graph';
import { VisualEngine } from './engine/visual-engine';
import { NodeEditor } from './components/NodeEditor';
import { AmbientPanel, Inspector, MediaPanel, OutputControls, SensorPanel, TimelinePanel } from './components/Panels';
import { ArduinoTerminal } from './components/ArduinoTerminal';
import { BinaryInputs } from './shared/arduino';
import { MappingEditor } from './components/MappingEditor';
import { cueLabel, text } from './i18n';

const emptyChannels=[0,0,0,0,0,0,0,0];
const effectIds:EffectId[]=['disperse','blocks','warp','vortex','lightPath','tide'];

export function App(){
  const [project,setProjectState]=useState<StudioProject>(()=>createDefaultProject());
  const language=project.ui.language;const t=(zh:string,en:string)=>text(language,zh,en);
  const projectRef=useRef(project);const [dirty,setDirty]=useState(false);const [projectPath,setProjectPath]=useState<string>();
  const [selected,setSelected]=useState<string>();const [mode,setMode]=useState<'graph'|'ambient'|'timeline'|'mapping'|'performance'|'arduino'>('arduino');
  const [channels,setChannels]=useState<number[]>(emptyChannels);const channelsRef=useRef<number[]>(emptyChannels);
  const [touchTelemetry,setTouchTelemetry]=useState<SensorFrame['touch']>();
  const touchReady=useRef(false);
  const [ports,setPorts]=useState<SerialPortInfo[]>([]);const [connected,setConnected]=useState(false);const connectedRef=useRef(false);const [displays,setDisplays]=useState<DisplayInfo[]>([]);const [outputOpen,setOutputOpen]=useState(false);
  const [globalState,setGlobalState]=useState<'running'|'final-releasing'|'standby'>('standby');
  const [performance,setPerformance]=useState<PerformanceInfo>({fps:0,frameMs:0,quality:'high',serialConnected:false,globalState:'standby'});
  const [notice,setNotice]=useState('系统就绪');const [finalHigh,setFinalHigh]=useState(false);
  const processors=useRef(Array.from({length:8},()=>new EnvelopeProcessor()));const machine=useRef(new GlobalStateMachine());const cueRuntime=useRef(new CueRuntime());const cueHigh=useRef(Array(8).fill(false));
  const binaryInputs=useRef(new BinaryInputs());
  const emotionSequence=useRef(new EmotionSequence());const [activeEmotion,setActiveEmotion]=useState<number>();const [emotionRemaining,setEmotionRemaining]=useState(0);
  const lastUiUpdate=useRef(0);const lastGlobalState=useRef<'running'|'final-releasing'|'standby'>('standby');
  const lastFrameAt=useRef(0);const lastSeq=useRef(-1);
  const playlistIndex=useRef(0);const playlistStarted=useRef(0);const [playlistPlaying,setPlaylistPlaying]=useState(false);const playlistPlayingRef=useRef(false);
  const preview=useRef<HTMLCanvasElement>(null);const previewHost=useRef<HTMLDivElement>(null);const [mappingFullscreen,setMappingFullscreen]=useState(false);const engine=useRef<VisualEngine|undefined>(undefined);const lastTick=useRef(performanceNow());const effectValues=useRef(Object.fromEntries(effectIds.map(id=>[id,0])) as Record<EffectId,number>);

  const setProject=useCallback((next:StudioProject,mark=true)=>{projectRef.current=next;setProjectState(next);if(mark)setDirty(true);},[]);
  const message=(zh:string,en:string)=>text(projectRef.current.ui.language,zh,en);
  useEffect(()=>{touchReady.current=false;binaryInputs.current.reset();window.centopia.arduino.configureTouch(project.arduino.wiring==='capacitive'?project.arduino.touch:null).catch(error=>setNotice(String(error)));},[project.arduino.wiring,project.arduino.touch]);

  useEffect(()=>{restartPreview(false);return()=>engine.current?.dispose();},[]);
  useEffect(()=>{if(mode==='performance'){engine.current?.dispose();engine.current=undefined;return;}const frame=requestAnimationFrame(()=>{if(preview.current&&!engine.current)restartPreview(false);});return()=>cancelAnimationFrame(frame);},[mode]);
  useEffect(()=>{const fullscreen=()=>setMappingFullscreen(document.fullscreenElement===previewHost.current);document.addEventListener('fullscreenchange',fullscreen);return()=>document.removeEventListener('fullscreenchange',fullscreen);},[]);
  useEffect(()=>{window.centopia.serial.list().then(setPorts);window.centopia.output.listDisplays().then(setDisplays);const offFrame=window.centopia.serial.onFrame(frame=>ingest(frame));const offStatus=window.centopia.serial.onStatus(status=>{const active=Boolean(status.connected);connectedRef.current=active;setConnected(active);if(!active){channelsRef.current=[...emptyChannels];setChannels([...emptyChannels]);setFinalHigh(false);lastFrameAt.current=0;binaryInputs.current.reset();}setNotice(active?`${message('Arduino 已连接','Arduino connected')} · ${status.path}`:status.error??message('Arduino 已断开','Arduino disconnected'));});const offOutput=window.centopia.output.onStatus(status=>{setOutputOpen(status.open);if(!status.open)setTimeout(()=>restartPreview(true),120);});const offCommand=window.centopia.runtime.onCommand(command=>command==='final'?triggerFinal():resetFinal());return()=>{offFrame();offStatus();offOutput();offCommand();};},[]);

  useEffect(()=>{const timer=setInterval(()=>{
    const now=performanceNow(),dt=Math.min(100,now-lastTick.current);lastTick.current=now;const p=projectRef.current;
    if(connectedRef.current&&lastFrameAt.current&&Date.now()-lastFrameAt.current>500){channelsRef.current=channelsRef.current.map(value=>value*Math.exp(-dt/600));setChannels([...channelsRef.current]);}
    const samples=processors.current.map((processor,index)=>processor.update(channelsRef.current[index]??0,p.nodes.find(n=>n.channel===index)?.envelope??p.serial.channels[index],dt));
    const hardwareFresh=connectedRef.current&&Date.now()-lastFrameAt.current<=500&&(p.arduino.wiring!=='capacitive'||touchReady.current);
    if(!hardwareFresh)binaryInputs.current.reset();
    const binaryConfig=p.arduino.wiring==='capacitive'?{...p.arduino,debounceMs:0,channels:p.arduino.channels.map(c=>({...c,activeLow:false,threshold:.5}))}:p.arduino;
    const binaryRising=hardwareFresh?binaryInputs.current.update(channelsRef.current,binaryConfig,now):Array(8).fill(false);
    const rising=samples.map((sample,index)=>connectedRef.current?binaryRising[index]:(sample.triggered&&!cueHigh.current[index]));
    if((rising[7]&&p.arduino.takeover&&p.arduino.channels[7].enabled)||finalHigh)triggerFinal();
    rising.slice(0,7).forEach((fire,index)=>{if(fire&&p.arduino.takeover&&p.arduino.channels[index].enabled&&!cueRuntime.current.isEnding){startEmotion(index,now);if(playlistPlayingRef.current&&p.playlist.mode==='triggered'&&p.playlist.advanceChannel===index)advanceTimeline();}});
    samples.forEach((sample,index)=>{cueHigh.current[index]=sample.triggered;});
    const advance=emotionSequence.current.update(p.emotionSequence,now);if(advance==='ambient'){cueRuntime.current.deactivate(now);setActiveEmotion(undefined);}else if(typeof advance==='number'){cueRuntime.current.trigger(advance,now,p.cues[advance]);setActiveEmotion(advance);}machine.current.update(false,p.cues[7].durationMs,now);if(machine.current.state!==lastGlobalState.current){lastGlobalState.current=machine.current.state;setGlobalState(machine.current.state);}if(now-lastUiUpdate.current>=250){lastUiUpdate.current=now;setEmotionRemaining(emotionSequence.current.remaining(p.emotionSequence,now));}
    for(const id of effectIds)effectValues.current[id]=0;
    const particleEvent=cueRuntime.current.resolve(p.cues,now);
    const snapshot={project:p,effectValues:{...effectValues.current},particleEvent,transition:{progress:1}};
    engine.current?.apply(snapshot);window.centopia.output.publish(snapshot);
  },33);return()=>clearInterval(timer);},[finalHigh]);
  useEffect(()=>{if(!playlistPlaying){playlistStarted.current=0;return;}const timer=setInterval(()=>{const p=projectRef.current,items=p.playlist.items;if(p.playlist.mode!=='timed')return;if(!items.length){playTimeline(false);return;}const item=items[Math.min(playlistIndex.current,items.length-1)];if(Date.now()-playlistStarted.current>=item.durationMs)advanceTimeline();},100);return()=>clearInterval(timer);},[playlistPlaying]);

  function ingest(frame:SensorFrame){setTouchTelemetry(frame.touch);touchReady.current=Boolean(frame.touch?.synced);if(lastSeq.current>=0&&frame.seq>lastSeq.current+2)setNotice(`${message('Arduino 数据丢帧','Arduino dropped frames')}: ${frame.seq-lastSeq.current-1}`);lastSeq.current=frame.seq;lastFrameAt.current=Date.now();channelsRef.current=[...frame.channels];setChannels([...frame.channels]);setFinalHigh(projectRef.current.arduino.wiring!=='capacitive'&&frame.final===1);}
  function startEmotion(index:number,now=performanceNow()){const p=projectRef.current;cueRuntime.current.trigger(index,now,p.cues[index]);emotionSequence.current.trigger(index,now);setActiveEmotion(index);machine.current.activate();setNotice(`CH ${index+1} · ${cueLabel(p.cues[index].kind,p.ui.language)}`);}
  function triggerFinal(){if(cueRuntime.current.isEnding)return;emotionSequence.current.reset();setActiveEmotion(undefined);cueRuntime.current.trigger(7,performanceNow(),projectRef.current.cues[7]);machine.current.trigger();playlistPlayingRef.current=false;setPlaylistPlaying(false);setNotice(message('CH8 · 光芒消散，结束后保持暗场；点击恢复播放重新开始','CH8 · Light dissolving. Holds dark until Resume playback.'));}
  function resetFinal(){machine.current.reset();cueRuntime.current.reset();emotionSequence.current.reset();setActiveEmotion(undefined);setEmotionRemaining(0);processors.current.forEach(p=>p.reset());setFinalHigh(false);setNotice(message('已立即复原','Immediate reset complete'));}
  function triggerCue(index:number){if(index===7){triggerFinal();return;}if(cueRuntime.current.isEnding)return;startEmotion(index);}
  async function connect(path?:string){if(connected){await window.centopia.serial.disconnect();setConnected(false);}else if(path){await window.centopia.serial.connect(path);setProject({...projectRef.current,serial:{...projectRef.current.serial,path}});}}
  async function importMedia(){const result=await window.centopia.media.import();if(result.rejected.length)setNotice(message(`${result.rejected.length} 个格式不受支持，请转为 MP4/WebM`,`${result.rejected.length} unsupported file(s). Convert to MP4/WebM.`));if(!result.accepted.length)return;const p=projectRef.current;const newItems=result.accepted.map(asset=>({id:`playlist-${crypto.randomUUID()}`,assetId:asset.id,durationMs:5000}));setProject({...p,assets:[...p.assets,...result.accepted],activeMediaId:p.activeMediaId??result.accepted[0].id,standbyMediaId:p.standbyMediaId??result.accepted[0].id,playlist:{...p.playlist,items:[...p.playlist.items,...newItems]}});}
  async function locateMedia(asset:StudioProject['assets'][number]){const path=await window.centopia.media.locate(asset);if(!path)return;const p=projectRef.current;setProject({...p,assets:p.assets.map(item=>item.id===asset.id?{...item,path,missing:false}:item)});setNotice(`${message('已重新定位','Relocated')} ${asset.name}`);}
  function deleteMedia(id:string){const p=projectRef.current;const assets=p.assets.filter(asset=>asset.id!==id);const nextId=p.activeMediaId===id?assets[0]?.id:p.activeMediaId;setProject({...p,assets,activeMediaId:nextId,standbyMediaId:p.standbyMediaId===id?assets[0]?.id:p.standbyMediaId,playlist:{...p.playlist,items:p.playlist.items.filter(item=>item.assetId!==id)}});setNotice(message('素材已从项目中移除，原文件未删除','Media removed from project; source file was kept.'));}
  function playTimeline(value:boolean){playlistPlayingRef.current=value;setPlaylistPlaying(value);playlistIndex.current=0;playlistStarted.current=Date.now();const first=projectRef.current.playlist.items[0];if(value&&first)setProject({...projectRef.current,activeMediaId:first.assetId},false);setNotice(value?projectRef.current.playlist.mode==='timed'?message('时间线开始自动播放','Timeline auto-play started'):message('条件时间线已启用，等待 NEXT / CH 触发','Triggered timeline enabled; waiting for NEXT / CH'):message('时间线已停止','Timeline stopped'));}
  function advanceTimeline(){const p=projectRef.current,items=p.playlist.items;if(!items.length)return;let index=playlistIndex.current+1;if(index>=items.length){if(!p.playlist.loop){playTimeline(false);return;}index=0;}playlistIndex.current=index;playlistStarted.current=Date.now();setProject({...p,activeMediaId:items[index].assetId},false);setNotice(`时间线 → ${p.assets.find(asset=>asset.id===items[index].assetId)?.name??`轨道 ${index+1}`}`);}
  function restartPreview(notify=true){if(!preview.current)return;engine.current?.dispose();const next=new VisualEngine(preview.current);next.onPerformance=info=>{const value={...info,serialConnected:connectedRef.current,globalState:machine.current.state};setPerformance(value);window.centopia.runtime.reportPerformance(value);};next.onError=error=>setNotice(`${message('GPU 渲染错误','GPU render error')} · ${error.message}`);engine.current=next;const p=projectRef.current;void next.apply({project:p,effectValues:{...effectValues.current},particleEvent:cueRuntime.current.resolve(p.cues),transition:{progress:1}});if(notify)setNotice(message('主预览已刷新并恢复 GPU 显示','Main preview refreshed and GPU output restored'));}
  async function refreshDisplays(){restartPreview(false);if(outputOpen)await window.centopia.output.refresh();setDisplays(await window.centopia.output.listDisplays());setNotice(outputOpen?message('主预览与投影输出已刷新','Preview and projector output refreshed'):message('主预览已刷新','Main preview refreshed'));}
  async function toggleMappingFullscreen(){if(document.fullscreenElement)await document.exitFullscreen();else await previewHost.current?.requestFullscreen();}
  function toggleLanguage(){const next=language==='zh'?'en':'zh';setProject({...projectRef.current,ui:{...projectRef.current.ui,language:next}});setNotice(text(next,'系统就绪','SYSTEM READY'));}
  function resizeLayout(side:'left'|'right'|'preview',start:React.PointerEvent){const base={...projectRef.current.ui.layout},sx=start.clientX,sy=start.clientY;const move=(event:PointerEvent)=>{const next={...base};if(side==='left')next.leftWidth=Math.max(190,Math.min(520,base.leftWidth+event.clientX-sx));if(side==='right')next.rightWidth=Math.max(220,Math.min(520,base.rightWidth-(event.clientX-sx)));if(side==='preview')next.previewHeight=Math.max(22,Math.min(75,base.previewHeight+(event.clientY-sy)/Math.max(1,window.innerHeight)*100));setProject({...projectRef.current,ui:{...projectRef.current.ui,layout:next}},false);};const done=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',done);setDirty(true);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',done);}
  function resetLayout(){setProject({...projectRef.current,ui:{...projectRef.current.ui,layout:{leftWidth:260,rightWidth:270,previewHeight:42}}});}
  async function openProject(){try{const result=await window.centopia.project.open();if(!result)return;resetFinal();playTimeline(false);binaryInputs.current.reset();channelsRef.current=[...emptyChannels];setChannels([...emptyChannels]);setProject(result.project,false);setProjectPath(result.path);setDirty(false);setNotice(`${text(result.project.ui.language,'已打开','Opened')} ${result.project.name}`);}catch(error){setNotice(String(error));}}
  async function save(as=false){try{const path=as?await window.centopia.project.saveAs(projectRef.current):await window.centopia.project.save(projectRef.current);if(path){setProjectPath(path);setDirty(false);setNotice(message('项目已保存（包含常态力场与量子点参数）','Project saved, including ambient field and quantum-dot settings.'));}}catch(error){setNotice(String(error));}}
  async function exportSettings(){try{setNotice(message('正在导出设置与素材…','Exporting settings and media…'));const path=await window.centopia.project.exportPortable(projectRef.current);setNotice(path?message('已导出：','Exported: ')+path:message('已取消','Cancelled'));}catch(error){setNotice(String(error));}}
  const selectedNode=useMemo(()=>project.nodes.find(n=>n.id===selected),[project.nodes,selected]);
  const setVirtual=(index:number,value:number)=>{const next=[...channelsRef.current];next[index]=value;channelsRef.current=next;setChannels(next);};

  return <main className={`app mode-${mode}`} style={{'--left-width':`${project.ui.layout.leftWidth}px`,'--right-width':`${project.ui.layout.rightWidth}px`,'--preview-height':`${project.ui.layout.previewHeight}%`} as React.CSSProperties}>
    <header className="topbar"><div className="brand"><i/><b>CENTOPIA</b><span>MAPPING STUDIO / V1</span></div><div className="project-title"><strong>{project.name}</strong>{dirty&&<i>●</i>}<small>{projectPath??t('未保存项目','UNSAVED PROJECT')}</small></div><nav><button onClick={openProject}>{t('打开','OPEN')}</button><button onClick={()=>save(false)}>{t('保存','SAVE')}</button><button onClick={()=>save(true)}>{t('另存','SAVE AS')}</button><button onClick={resetFinal}>{t('恢复播放','RESUME')}</button><button className={mode==='arduino'?'active':''} onClick={()=>setMode('arduino')}>Arduino</button><button className={mode==='ambient'?'active':''} onClick={()=>setMode('ambient')}>{t('常态力场','AMBIENT FIELD')}</button><button className={mode==='timeline'?'active':''} onClick={()=>setMode('timeline')}>{t('时间线','TIMELINE')}</button><button className={mode==='mapping'?'active':''} onClick={()=>setMode('mapping')}>UV</button><button className={mode==='performance'?'active':''} onClick={()=>setMode('performance')}>{t('演出','LIVE')}</button><button onClick={toggleLanguage}>{language==='zh'?'EN':'中文'}</button></nav></header>
    {mode!=='performance'&&<div className="workspace"><aside className="leftbar"><MediaPanel language={language} assets={project.assets} active={project.activeMediaId} onImport={importMedia} onSelect={id=>setProject({...project,activeMediaId:id})} onLocate={locateMedia} onDelete={deleteMedia}/><SensorPanel language={language} values={channels} cues={project.cues} connected={connected} ports={ports} onConnect={connect} onVirtual={setVirtual} onTrigger={triggerCue}/></aside><div className="vertical-split left-split" onDoubleClick={resetLayout} onPointerDown={event=>resizeLayout('left',event)}/>
      <section className="center"><div ref={previewHost} className={`preview ${mappingFullscreen?'mapping-fullscreen':''}`}><canvas ref={preview}/>{mode==='mapping'&&<MappingEditor mapping={project.mapping} onChange={value=>setProject({...project,mapping:{...project.mapping,...value}})}/>}<button className="preview-mode-button" onClick={()=>{const modes=['eco','standard','high','1080p','auto'] as const;const next=modes[(modes.indexOf(project.mapping.previewMode)+1)%modes.length];setProject({...project,mapping:{...project.mapping,previewMode:next,previewScale:next==='eco'?.25:next==='standard'?.5:.75}});}}>{project.mapping.previewMode.toUpperCase()}</button><div className="preview-hud"><span>{performance.fps.toFixed(0)} FPS · {project.activeMediaId?t('常态素材：持续点阵播放','AMBIENT MEDIA: CONTINUOUS DOT PLAYBACK'):t('无素材：黑色点阵','NO MEDIA: BLACK DOT FIELD')}</span><span><i className="preview-quality">PREVIEW {project.mapping.previewMode==='1080p'?'1920×1080':project.mapping.previewMode.toUpperCase()}</i> · 4K OUT · {performance.quality.toUpperCase()}</span></div></div><div className="horizontal-split" onPointerDown={event=>resizeLayout('preview',event)}/>
      {mode==='graph'?<div className="graph"><NodeEditor language={language} cues={project.cues} nodes={project.nodes} edges={project.edges} values={channels} routingEnabled={project.routing.enabled} onRouting={enabled=>setProject({...project,routing:{enabled}})} onSelect={setSelected} onChange={(nodes,edges)=>setProject({...project,nodes,edges})}/></div>
      :mode==='arduino'?<ArduinoTerminal project={project} channels={channels} connected={connected} ports={ports} touchTelemetry={touchTelemetry} activeEmotion={activeEmotion} emotionRemaining={emotionRemaining} onProject={setProject} onRefresh={()=>window.centopia.serial.list().then(setPorts)} onConnect={port=>connect(port).catch(error=>setNotice(String(error)))} onTrigger={triggerCue} onExport={exportSettings} onImport={openProject}/>
      :mode==='ambient'?<AmbientPanel language={language} project={project} onProject={setProject}/>
      :mode==='timeline'?<TimelinePanel language={language} project={project} playing={playlistPlaying} onProject={setProject} onPlay={playTimeline} onNext={advanceTimeline} onSelect={id=>setProject({...project,activeMediaId:id},false)}/>
      :<div className="mapping-tools"><h2>{project.mapping.editorLayer==='source'?t('素材取景框','SOURCE FRAME'):project.mapping.controlMode==='basic'?t('基础 UV 四点校正','BASIC FOUR-POINT UV'):t('复杂 UV 网格校正','ADVANCED UV GRID')}</h2><p>{t('先用取景框选择素材区域，再用 UV 控制投影表面。取景框、预览模式和布局都会保存。','Choose the source region first, then shape the projector surface with UV. Frame, preview and layout are saved.')}</p><OutputControls language={language} project={project} displays={displays} outputOpen={outputOpen} onProject={setProject} onOpen={()=>window.centopia.output.open(project.mapping.displayId)} onClose={()=>window.centopia.output.close()} onRefresh={refreshDisplays}/><div className="mapping-options"><button className={project.mapping.editorLayer==='source'?'active':''} onClick={()=>setProject({...project,mapping:{...project.mapping,editorLayer:'source'}})}>{t('取景框','SOURCE FRAME')}</button><button className={project.mapping.editorLayer==='uv'?'active':''} onClick={()=>setProject({...project,mapping:{...project.mapping,editorLayer:'uv'}})}>UV</button><label>{t('UV控制','UV MODE')}<select disabled={project.mapping.editorLayer==='source'} value={project.mapping.controlMode} onChange={e=>setProject({...project,mapping:{...project.mapping,controlMode:e.target.value as 'basic'|'grid'}})}><option value="basic">{t('基础 · 四点','BASIC · FOUR POINTS')}</option><option value="grid">{t('复杂 · 内部网格','ADVANCED · INNER GRID')}</option></select></label><label>{t('预览','PREVIEW')}<select value={project.mapping.previewMode} onChange={e=>{const previewMode=e.target.value as StudioProject['mapping']['previewMode'];setProject({...project,mapping:{...project.mapping,previewMode,previewScale:previewMode==='eco'?.25:previewMode==='standard'?.5:.75}})}}><option value="eco">ECO 25%</option><option value="standard">STANDARD 50%</option><option value="high">HIGH 75%</option><option value="1080p">1080P</option><option value="auto">AUTO</option></select></label><label>{t('适配','FIT')}<select value={project.mapping.fit} onChange={e=>setProject({...project,mapping:{...project.mapping,fit:e.target.value as 'fill'}})}><option value="fill">Fill</option><option value="fit">Fit</option><option value="stretch">Stretch</option></select></label><button onClick={toggleMappingFullscreen}>{mappingFullscreen?t('退出全屏校正','EXIT FULLSCREEN'):t('全屏校正','FULLSCREEN CALIBRATION')}</button><button onClick={()=>setProject({...project,mapping:{...project.mapping,sourceFrame:{x:0,y:0,width:1,height:1},quad:{topLeft:[0,0],topRight:[1,0],bottomRight:[1,1],bottomLeft:[0,1]},grid:defaultGrid(project.mapping.grid.columns)}})}>{t('重置取景与 UV','RESET FRAME + UV')}</button></div></div>}</section>
      <div className="vertical-split right-split" onDoubleClick={resetLayout} onPointerDown={event=>resizeLayout('right',event)}/><Inspector language={language} project={project} selected={selectedNode} onProject={setProject}/></div>}
    {mode==='performance'&&<section className="performance"><div className="performance-card"><div className="perf-brand">CENTOPIA <span>LIVE</span></div><div className="perf-state"><small>GLOBAL STATE</small><strong>{globalState.toUpperCase()}</strong></div><div className="perf-metrics"><div><b>{performance.fps.toFixed(0)}</b><span>FPS</span></div><div><b>{connected?'ON':'SIM'}</b><span>ARDUINO</span></div><div><b>4K</b><span>OUTPUT</span></div></div><div className="perf-actions"><button className="final-button" onClick={triggerFinal}>CH8 · END<small>{project.cues[7].durationMs/1000} SEC DISSOLVE</small></button><button onClick={resetFinal}>{t('立即复原','RESET NOW')}</button><button className={project.mapping.blackout?'active danger':''} onClick={()=>setProject({...project,mapping:{...project.mapping,blackout:!project.mapping.blackout}})}>BLACKOUT</button><button onClick={()=>window.centopia.output.open(project.mapping.displayId)}>{t('开启投影','OPEN OUTPUT')}</button></div></div></section>}
    <footer><span className={connected?'online':''}>● {notice}</span><span>FINAL: {finalHigh?'HIGH':'LOW'}</span><span>{globalState.toUpperCase()}</span></footer>
  </main>;
}
function performanceNow(){return typeof performance==='undefined'?Date.now():performance.now();}
